export const GET_USER_FROM_LOCALE = "GET_USER_FROM_LOCALE";

export const ON_USER_BALANCE = "ON_USER_BALANCE";

export const GET_TRANSACTIONS_REQUEST = "GET_TRANSACTIONS_REQUEST";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";

export const UPDATE_PENDING_TX = "UPDATE_PENDING_TX";