export const ON_WEB3_CHECK = "ON_WEB3_CHECK";

export const ON_WEB3_ACCOUNT = "ON_WEB3_ACCOUNT";
export const ON_WEB3_ACCOUNT_FAIL= "ON_WEB3_ACCOUNT_FAIL";

export const ON_WEB3_BALANCE = "ON_WEB3_BALANCE";
export const ON_WEB3_BALANCE_FAIL = "ON_WEB3_BALANCE_FAIL";


export const ON_WEB3_WTOL_BALANCE = "ON_WEB3_WTOL_BALANCE";
export const ON_WEB3_USDC_BALANCE = "ON_WEB3_WTOL_BALANCE";
export const ON_WEB3_ETH_BALANCE = "ON_WEB3_WTOL_BALANCE";

export const ON_TOKENS_OWNED_BALANCE = "ON_TOKENS_OWNED_BALANCE";
export const ON_TOKENS_OWNED_RESET = "ON_TOKENS_OWNED_RESET";