export const GET_COLLECTIONS_REQUEST = "GET_COLLECTIONS_REQUEST";
export const GET_COLLECTIONS_SUCCESS = "GET_COLLECTIONS_SUCCESS";
export const GET_COLLECTIONS_FAIL = "GET_COLLECTIONS_FAIL";

export const GET_COLLECTIONS_OF_THE_ISSUER_REQUEST = "GET_COLLECTIONS_REQUEST";
export const GET_COLLECTIONS_OF_THE_ISSUER_SUCCESS = "GET_COLLECTIONS_SUCCESS";
export const GET_COLLECTIONS_OF_THE_ISSUER_FAIL = "GET_COLLECTIONS_FAIL";


export const GET_ITEMS_REQUEST = "GET_ITEMS_REQUEST";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";

export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS";
export const GET_ITEM_FAIL = "GET_ITEM_FAIL";

export const CLAIM_ITEM_REQUEST = "CLAIM_ITEM_REQUEST";
export const CLAIM_ITEM_SUCCESS = "CLAIM_ITEM_SUCCESS";
export const CLAIM_ITEM_FAIL = "CLAIM_ITEM_FAIL";
export const CLAIM_ITEM_RESET = "CLAIM_ITEM_RESET";

export const SELECT_COLLECTION = "SELECT_COLLECTION";
export const DESELECT_COLLECTION = "DESELECT_COLLECTION";

export const PROGRESS_DONE = "PROGRESS_DONE";