export const ON_WEB3_CHECK = "ON_WEB3_CHECK";

export const ON_WEB3_ACCOUNT = "ON_WEB3_ACCOUNT";
export const ON_WEB3_ACCOUNT_FAIL= "ON_WEB3_ACCOUNT_FAIL";

export const ON_WEB3_BALANCE = "ON_WEB3_BALANCE";
export const ON_WEB3_BALANCE_FAIL = "ON_WEB3_BALANCE_FAIL";


export const ON_WEB3_WTOL_BALANCE = "ON_WEB3_WTOL_BALANCE";
export const ON_WEB3_USDC_BALANCE = "ON_WEB3_USDC_BALANCE";
export const ON_WEB3_ETH_BALANCE = "ON_WEB3_ETH_BALANCE";

export const ON_INPUT_HIGHER_THAN_BALANCE = "ON_INPUT_HIGHER_THAN_BALANCE"

export const ON_WTOL_USDC_POOL = "ON_WTOL_USDC_POOL"
export const ON_WTOL_ETH_POOL = "ON_WTOL_ETH_POOL"
export const ON_USDC_ETH_POOL = "ON_USDC_ETH_POOL"
