export const ON_WEB3_CHECK = "ON_WEB3_CHECK";

export const ON_WEB3_ACCOUNT = "ON_WEB3_ACCOUNT";
export const ON_WEB3_ACCOUNT_FAIL= "ON_WEB3_ACCOUNT_FAIL";

export const ON_WEB3_BALANCE = "ON_WEB3_BALANCE";
export const ON_WEB3_BALANCE_FAIL = "ON_WEB3_BALANCE_FAIL";


export const ON_WEB3_WTOL_BALANCE = "ON_WEB3_WTOL_BALANCE";
export const ON_WEB3_USDC_BALANCE = "ON_WEB3_USDC_BALANCE";
export const ON_WEB3_ETH_BALANCE = "ON_WEB3_ETH_BALANCE";

export const ON_INPUT_HIGHER_THAN_BALANCE = "ON_INPUT_HIGHER_THAN_BALANCE"

export const ON_WTOL_USDC_POOL = "ON_WTOL_USDC_POOL"
export const ON_WTOL_ETH_POOL = "ON_WTOL_ETH_POOL"
export const ON_USDC_ETH_POOL = "ON_USDC_ETH_POOL"

export const ON_ADDRESS_LIQUIDITY = "ON_ADDRESS_LIQUIDITY"
export const ON_ADDRESS_HAS_LIQUIDITY = "ON_ADDRESS_HAS_LIQUIDITY"
export const ON_ADDRESS_HAS_NO_LIQUIDITY = "ON_ADDRESS_HAS_NO_LIQUIDITY"

//Pair reducer
export const ON_GET_PAIRS_ADDRESS="ON_GET_PAIRS_ADDRESS"

export const ON_CALCULATE_OUTPUT_AMOUNT="ON_CALCULATE_OUTPUT_AMOUNT"
export const ON_CALCULATE_INPUT_AMOUNT="ON_CALCULATE_INPUT_AMOUNT"

export const ON_SC_BALANCE_FOR_TOKEN_A="ON_SC_BALANCE_FOR_TOKEN_A"
export const ON_SC_BALANCE_FOR_TOKEN_A_RECEIPT="ON_SC_BALANCE_FOR_TOKEN_A_RECEIPT"

export const ON_SC_BALANCE_FOR_TOKEN_B="ON_SC_BALANCE_FOR_TOKEN_B"
export const ON_SC_BALANCE_FOR_TOKEN_B_RECEIPT="ON_SC_BALANCE_FOR_TOKEN_B_RECEIPT"

export const ON_GET_TOTAL_SUPPLY="ON_GET_TOTAL_SUPPLY"

export const ON_GET_ADDRESS_BALANCE="ON_GET_ADDRESS_BALANCE"

export const ON_GET_MINTING_AMOUNT="ON_GET_MINTING_AMOUNT"

export const ON_CALCULATE_AMOUNTS_IN="ON_CALCULATE_AMOUNTS_IN";
export const ON_CALCULATE_AMOUNTS_OUT="ON_CALCULATE_AMOUNTS_OUT"
// export const ON_CALCULATE_AMOUNTS_IN_RECEIPT="ON_CALCULATE_AMOUNTS_IN_RECEIPT"
// export const ON_CALCULATE_AMOUNTS_OUT_RECEIPT="ON_CALCULATE_AMOUNTS_OUT_RECEIPT"
